### ISSUE TITLE
Is this package needed?

### ISSUE THREAD

**Issue by tjohnston01** [jupyterhub/jupyterhub-labextension#3]
In the default jupyterhub_config.py, there is this entry:
```
#  - You can set this to `/lab` to have JupyterLab start by default, rather than Jupyter Notebook.
#c.Spawner.default_url = '/lab
```

Is this assuming I have jupyterhub-labextension installed? Or is there another way to launch jupyterlab from jupyterhub without it?

**Comment by minrk** [comment]
The idea is for JupyterHub integration - e.g. a link back to the control panel, etc., and a place to put any future single-user extensions that JupyterHub provides.

**Comment by tjohnston01** [comment]
Ah, okay. Thanks for clarifying.
